version: '3.7'

services:

  sample:
    container_name: sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      -  "5000:5000"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start